- name: Install PHP
  apt: pkg={{item}} state=latest
  with_items:
    - php7.0-fpm
    - php7.0-imap
    - php7.0-mysql

- name: Copy php.ini
  copy: src=php.ini dest=/etc/php/7.0/fpm/php.ini backup=yes

