- name: Install PHP
  apt:
    pkg:
      - composer
      - php-fpm
      - php-imap
      - php-intl
      - php-mbstring
      - php-mysql
    state: latest

- name: Copy php.ini
  copy:
    src: php.ini
    dest: /etc/php/7.3/fpm/php.ini
    backup: yes

