- name: Install PHP
  apt: pkg={{item}} state=latest
  with_items:
    - composer
    - php-fpm
    - php-imap
    - php-intl
    - php-mbstring
    - php-mysql

- name: Copy php.ini
  copy: src=php.ini dest=/etc/php/7.2/fpm/php.ini backup=yes

