- name: Add jenkins user
  user:
    name: jenkins
    groups: shadow
    shell: /bin/zsh
    state: present
    system: yes

- name: Ensure home directory
  file:
    path: /home/jenkins
    owner: jenkins
    group: jenkins
    state: directory

- name: Ensure .ssh directory
  file:
    path: /home/jenkins/.ssh
    owner: jenkins
    group: jenkins
    state: directory

- name: Copy id_rsa file
  copy:
    src: id_rsa
    dest: /home/jenkins/.ssh/id_rsa
    owner: jenkins
    group: jenkins
    mode: 600

- name: Add jenkins apt key
  apt_key:
    url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
    state: present

- name: Add jenkins repository
  apt_repository:
    repo: "deb http://pkg.jenkins-ci.org/debian binary/"
    state: present
    update_cache: yes

- name: Install fabric, jenkins and openjdk
  apt:
    pkg:
      - fabric
      - jenkins
      - openjdk-11-jre-headless
    state: latest
  notify: restart jenkins

- name: Copy jenkins site settings
  template:
    src: h2o.conf.j2
    dest: /etc/h2o/h2o.conf
    backup: yes
  notify: restart h2o

