---
- name: "Add jenkins user"
  user:
    name: "jenkins"
    groups: "shadow"
    shell: "/bin/zsh"
    state: "present"
    system: true

- name: "Ensure home directory"
  file:
    path: "/home/jenkins"
    owner: "jenkins"
    group: "jenkins"
    state: "directory"

- name: "Ensure .ssh directory"
  file:
    path: "/home/jenkins/.ssh"
    owner: "jenkins"
    group: "jenkins"
    state: "directory"

- name: "Copy id_rsa file"
  copy:
    src: "id_rsa"
    dest: "/home/jenkins/.ssh/id_rsa"
    owner: "jenkins"
    group: "jenkins"
    mode: 0600

- name: "Add jenkins apt keys"
  ansible.builtin.get_url:
    url: "https://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
    dest: "/usr/share/keyrings/jenkins-ci.org.gpg"

- name: "Add jenkins repository"
  ansible.builtin.copy:
    src: "sources.list.d/jenkins.sources"
    dest: "/etc/apt/sources.list.d"
    backup: true

- name: "Install fabric, jenkins and openjdk"
  apt:
    name:
      - "fabric"
      - "jenkins"
      - "openjdk-11-jre-headless"
    state: "latest"
  notify: "restart jenkins"

- name: "Copy jenkins site settings"
  template:
    src: "h2o.conf.j2"
    dest: "/etc/h2o/h2o.conf"
    backup: true
  notify: "restart h2o"
