- name: Install Let's encrypt
  apt: pkg={{item}} state=latest
  with_items:
    - letsencrypt

- name: Ensure config direcotry
  file: path=/etc/letsencrypt state=directory

- name: Copy client.conf
  template: src=client.conf.j2 dest=/etc/letsencrypt/client.conf backup=yes

