- name: Install NSD
  apt: pkg={{item}} state=latest
  with_items:
    - nsd

- name: Ensure zone files directory
  file: path=/etc/nsd/zone state=directory

- name: Ensure sample files directory
  file: path=/etc/nsd/samples state=directory

- name: Copy nsd.conf
  copy: src=nsd.conf dest=/etc/nsd/nsd.conf backup=yes
  notify: restart nsd

- name: Copy config file
  copy: src={{item}} dest=/etc/nsd/nsd.conf.d/{{item}} backup=yes
  with_items:
    - server.conf
  notify: restart nsd

- name: Copy zone config file
  template: src={{item}} dest=/etc/nsd/nsd.conf.d/{{item}} backup=yes
  with_items:
    - zone.conf
  notify: restart nsd

- name: Copy sample zone file
  copy: src={{item}} dest=/etc/nsd/samples/{{item}} backup=yes
  with_items:
    - zonefile
    - zonefile.rev

