---
hosts: "localhost"
dbname: "postfix"
myhostname: "example.com"
mydestinations:
    - "{{myhostname}}"
    - "localhost"
    - "localhost.localdomain"
mynetworks:
    - "127.0.0.0/8"
    - "[::ffff:127.0.0.0]/104"
    - "[::1]/128"
relay_domains:
    example.com: "mail.example.com"
