---
- name: "Generate locale"
  locale_gen:
    name: "{{item}}"
    state: "present"
  with_items: "{{locales}}"

- name: "Update locale"
  shell: |
    dpkg-reconfigure --frontend noninteractive locales
    update-locale LANG="C.UTF-8" LANGUAGE="C.UTF-8" LC_ALL="C.UTF-8"

- name: "Set timezone"
  shell: |
    echo "Asia/Tokyo" > /etc/timezone
    dpkg-reconfigure --frontend noninteractive tzdata
