- name: Generate locale
  locale_gen: name={{item}} state=present
  with_items:
    - en_GB.UTF-8
    - en_US.UTF-8
    - ja_JP.UTF-8

- name: Update locale
  shell: |
    dpkg-reconfigure --frontend noninteractive locales
    update-locale LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: Set timezone
  shell: |
    echo Asia/Tokyo > /etc/timezone
    dpkg-reconfigure --frontend noninteractive tzdata

