---
- name: "Install Squid"
  apt:
    name: "squid"
    state: "latest"

- name: "Copy squid.conf"
  copy:
    src: "squid.conf"
    dest: "/etc/squid/squid.conf"
    backup: true
  notify: "restart squid"
