- name: Create user group
  group: name={{item}} state=present
  with_items:
    - fujimakishouten

- name: Create share directory
  file: path=/usr/share/fujimakishouten mode=775 group=fujimakishouten state=directory

- name: Create user password directory
  file: path=/usr/share/fujimakishouten/users mode=770 group=fujimakishouten state=directory

- name: Copy password files
  copy: src=fujimakishouten dest=/usr/share/fujimakishouten/users/fujimakishouten mode=640 group=fujimakishouten backup=yes

- name: Register username
  shell: cat /usr/share/fujimakishouten/users/fujimakishouten | cut --delimiter=":" --fields=1
  register: user

- name: Register password
  shell: cat /usr/share/fujimakishouten/users/fujimakishouten | cut --delimiter=":" --fields=2
  register: password

- name: Hash password
  shell: mkpasswd --method=SHA-512 {{password.stdout}}
  register: hash

- name: Register user
  user: name={{user.stdout}} group=fujimakishouten groups="adm" password={{hash.stdout}} shell=/bin/bash append=yes

- name: Add to sudoers
  shell: /bin/bash -c "echo 'fujimakishouten  ALL=(ALL:ALL) ALL'" > /etc/sudoers.d/fujimakishouten

- name: Create home directory
  file: path=/home/fujimakishouten mode=755 owner=fujimakishouten group=fujimakishouten state=directory

- name: Create SSH directory
  file: path=/home/fujimakishouten/.ssh mode=755 owner=fujimakishouten group=fujimakishouten state=directory

- name: Copy SSH public key
  copy: src=authorized_keys dest=/home/fujimakishouten/.ssh/authorized_keys mode=644 owner=fujimakishouten group=fujimakishouten backup=yes

