- name: Install packages
  apt:
    name={{item}}
    state=latest
    update_cache=yes
  with_items: 
    - iptables
    - iptables-persistent

- name: Copy rules
  copy:
    src: "{{item}}"
    dest: /etc/iptables
    backup: yes
  with_items:
    - rules.v4
    - rules.v6

