- name: Install opendmarc
  apt: pkg={{item}} state=latest
  with_items:
    - opendmarc

- name: Ensure config directory
  file: path=/etc/opendmarc state=directory

- name: Get original opendmarc.conf status
  stat: path=/etc/opendkim.conf
  register: opendmarc

- name: Move opendmarc.conf to opendmarc directory
  command: mv /etc/opendmarc.conf /etc/opendmarc/opendmarc.conf
  when: not opendkim.stat.islnk

- name: Copy opendmarc.conf
  copy: src=opendmarc.conf dest=/etc/opendmarc/opendmarc.conf backup=yes
  notify: restart opendmarc

- name: Link opendmarc.conf
  file: src=/etc/opendmarc/opendmarc.conf dest=/etc/opendmarc.conf state=link
  when: not opendkim.stat.islnk

