---
- hosts: "email-secondary"
  become: true
  become_user: "root"
  roles:
    - "../roles/letsencrypt"
    - "../roles/mysql"
    - "../roles/clamsmtp"
    - "../roles/opendkim"
    - "../roles/opendmarc"
    - "../roles/spamassassin"
    - "../roles/postfix-secondary"
    - "../roles/dovecot"
