---
- name: "Add cassandra apt key"
  ansible.builtin.get_url:
    url: "https://www.apache.org/dist/cassandra/KEYS"
    dest: "/usr/share/keyrings/cassandra.gpg"

- name: "Add cassandra repository"
  template:
    src: "cassandra.sources.j2"
    dest: "/etc/apt/sources.list.d/cassandra.sources"
    backup: true

- name: "Update cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Install pip"
  apt:
    name:
      - "python3-pip"
    state: "latest"

- name: "Install cassandra driver"
  pip:
    name:
      - "cassandra-driver"
    state: "present"

- name: "Copy environment file"
  copy:
    src: "environment"
    dest: "/etc/environment"
    backup: true

- name: "Install cassandra"
  apt:
    name:
      - "cassandra"
      - "cassandra-tools"
    state: "latest"
  notify: "restart cassandra"

- name: "Copy cassandra settings"
  template:
    src: "{{item}}.j2"
    dest: "/etc/cassandra/{{item}}"
    backup: true
  with_items:
    - "cassandra-env.sh"
    - "cassandra.yaml"
  notify: "restart cassandra"
