- name: Add cassandra apt key
  apt_key:
    url: https://www.apache.org/dist/cassandra/KEYS
    keyring: /usr/share/keyrings/cassandra.gpg
    state: present

- name: Add cassandra repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/cassandra.gpg] http://www.apache.org/dist/cassandra/debian {{release_series}} main"
    state: present
    update_cache: yes

- name: Add cassandra source repository
  apt_repository:
    repo: "deb-src [arch=amd64 signed-by=/usr/share/keyrings/cassandra.gpg] http://www.apache.org/dist/cassandra/debian {{release_series}} main"
    state: present
    update_cache: yes

- name: Install pip
  apt:
    name:
      - python3-pip
    state: latest

- name: Install cassandra driver
  pip:
    name:
      - cassandra-driver
    state: present

- name: Copy environment file
  copy:
    src: environment
    dest: /etc/environment
    backup: yes

- name: Install cassandra
  apt:
    name:
      - cassandra
      - cassandra-tools
    state: latest
  notify: restart cassandra

- name: Copy cassandra settings
  template:
    src: "{{item}}.j2"
    dest: /etc/cassandra/{{item}}
    backup: yes
  with_items:
    - cassandra-env.sh
    - cassandra.yaml
  notify: restart cassandra

