- name: Install Git
  apt:
    name: git
    state: latest

- name: Get nave.sh
  git:
    repo: https://github.com/isaacs/nave.git
    dest: /opt/nave
    update: yes

- name: Install node.js
  shell: /opt/nave/bin/nave usemain latest

- name: Recover permissions
  file:
    path: /usr/local
    owner: root
    group: staff
    recurse: yes

- name: Install global node modules
  shell: npm install --global istanbul mocha pm2

- name: Create root directory
  file:
    path: /var/lib/node
    state: directory

