---
- name: "Install mongodb"
  apt:
    name:
      - "mongodb"
    state: "latest"

- name: "Copy mongodb.conf"
  copy:
    src: "mongodb.conf"
    dest: "/etc/mongodb.conf"
    backup: true
  notify: "restart mongodb"
