- name: Install postfix
  apt: pkg={{item}} state=latest
  with_items:
    - postfix

- name: Get postfix user id
  command: id -u postfix
  register: uid

- name: Get postfix group id
  command: id -g postfix
  register: gid

- name: Copy master.cf
  copy: src=master.cf dest=/etc/postfix/master.cf backup=yes
  notify: restart postfix

- name: Copy main.cf
  template: src=main.cf.j2 dest=/etc/postfix/main.cf backup=yes
  notify: restart postfix

- name: Copy transport.cf
  template: src=transport.cf.j2 dest=/etc/postfix/transport.cf backup=yes
  notify: 
    - update transport db
    - restart postfix

