- name: Install unbound
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - unbound

- name: Copy server.conf
  copy:
    src: server.conf
    dest: /etc/unbound/unbound.conf.d/server.conf
    backup: yes
  notify: restart unbound

- name: Copy configs
  template:
      src: "{{item}}.j2"
      dest: /etc/unbound/unbound.conf.d/{{item}}
      backup: yes
  with_items:
    - local-data.conf
    - local-zone.conf
    - stub-zone.conf
  notify: restart unbound

