- name: Install h2o
  apt: pkg={{item}} state=latest
  with_items:
    - h2o

- name: Ensure dhparams directory
  file:
    path: /etc/h2o/dhparams
    state: directory

- name: Copy dhparams files
  copy:
    src: "{{item}}"
    dest: /etc/h2o/dhparams/{{item}}
  with_items:
    - default.pem

- name: Ensure host configuration file directory
  file:
    path: /etc/h2o/hosts
    state: directory

- name: Copy host configuration files
  template:
    src: host.conf.j2
    dest: /etc/h2o/hosts/{{item}}.conf
    backup: yes
  with_items: "{{domains}}"

- name: Copy h2o.conf file
  template:
    src: h2o.conf.j2
    dest: /etc/h2o/h2o.conf
    backup: yes

