---
- name: "Install nginx"
  apt:
    name:
      - "nginx"
    state: "latest"

- name: "Ensure dhparam file directory"
  file:
    path: "/etc/nginx/dhparams"
    state: "directory"

- name: "Copy dhparam file"
  copy:
    src: "default.pem"
    dest: "/etc/nginx/dhparams/default.pem"
    backup: true

- name: "Copy default site configuration"
  template:
    src: "default.j2"
    dest: "/etc/nginx/sites-available/default"
    backup: true
  notify: "restart nginx"
