- name: Install nginx
  apt: pkg={{item}} state=latest
  with_items:
    - nginx

- name: Ensure dhparam file directory
  file: path=/etc/nginx/dhparams state=directory

- name: Copy dhparam file
  copy: src=default.pem dest=/etc/nginx/dhparams/default.pem backup=yes

- name: Copy default site configuration
  template: src=default.j2 dest=/etc/nginx/sites-available/default backup=yes
  notify: restart nginx

