---
# - name: "Install required packages"
#   ansible.builtin.apt:
#     name:
#       - "apt-transport-https"
#       - "ca-certificates"
#       - "curl"
#       - "software-properties-common"
#     state: "latest"
#     update_cache: true

# - name: "Add docker keys"
#   ansible.builtin.get_url:
#     url: "https://download.docker.com/linux/debian/gpg"
#     dest: "/usr/share/keyrings/docker-ce.asc"

# - name: "Copy sources list"
#   ansible.builtin.copy:
#     src: "docker-ce.list"
#     dest: "/etc/apt/sources.list.d"

# - name: Install docker-ce
#   ansible.builtin.apt:
#     name:
#       - "docker-ce"
#       - "kubernetes-client"
#     state: "latest"
#     update_cache: true

- name: "Install docker"
  ansible.builtin.apt:
    name:
      - "docker.io"
      - "kubernetes-client"
    state: "latest"
    update_cache: true

- name: "Copy daemon.json"
  ansible.builtin.copy:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"
    backup: true
  notify: "restart docker"
