- name: Copy sources.list
  copy: src=sources.list dest=/etc/apt/sources.list backup=yes

- name: Update apt cache
  apt: update_cache=yes

- name: Install aptitude
  apt: pkg={{item}} state=latest
  with_items:
    - apache2-utils
    - aptitude
    - awscli
    - brotli
    - clamav
    - colordiff
    - convmv
    - curl
    - dnsutils
    - emacs24
    - git
    - global
    - htop
    - iotop
    - ipcalc
    - lhasa
    - lzip
    - nkf
    - pbzip2
    - pwgen
    - python3-venv
    - rar
    - rkhunter
    - screen
    - sl
    - sshfs
    - sudo
    - sysstat
    - tcpdump
    - telnet-ssl
    - tmux
    - tree
    - unrar
    - vim-nox
    - vrms
    - whois
    - zsh

