---
- name: "Install required packages"
  apt:
    name:
      - "apt-transport-https"
    state: "latest"

- name: "Add microsoft key"
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/usr/share/keyrings/microsoft.acs"

- name: "Copy sources list"
  copy:
    src: "sources.list.d/azure-cli.sources"
    dest: "/etc/apt/sources.list.d"

- name: "Update cache"
  apt:
    update_cache: true

- name: "Install azure-cli"
  apt:
    name:
      - "azure-cli"
    state: "latest"
