- name: "Install spamassassin"
  apt:
    name:
      - "spamassassin"
    state: "latest"

- name: "Copy config files"
  copy:
    src: "{{item}}"
    dest: "/etc/spamassassin/{{item}}"
    backup: true
  with_items:
    - "conf.d"
    - "local.cf"
    - "includes.cf"
  notify: "restart spamassassin"
