- name: Install spamassassin
  apt: pkg={{item}} state=latest
  with_items:
    - spamassassin

- name: Copy config files
  copy: src={{item}} dest=/etc/spamassassin/{{item}} backup=yes
  with_items:
    - conf.d
    - local.cf
    - includes.cf
  notify: restart spamassassin

